/*******************************************************************************
*    Alcugs H'uru server                                                       *
*                                                                              *
*    Copyright (C) 2004-2005  The Alcugs H'uru Server Team                     *
*    See the file AUTHORS for more info about the team                         *
*                                                                              *
*    This program is free software; you can redistribute it and/or modify      *
*    it under the terms of the GNU General Public License as published by      *
*    the Free Software Foundation; either version 2 of the License, or         *
*    (at your option) any later version.                                       *
*                                                                              *
*    This program is distributed in the hope that it will be useful,           *
*    but WITHOUT ANY WARRANTY; without even the implied warranty of            *
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             *
*    GNU General Public License for more details.                              *
*                                                                              *
*    You should have received a copy of the GNU General Public License         *
*    along with this program; if not, write to the Free Software               *
*    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA *
*                                                                              *
*    Please see the file COPYING for the full license.                         *
*    Please see the file DISCLAIMER for more details, before doing nothing.    *
*                                                                              *
*                                                                              *
*******************************************************************************/

/**
	URUNET 3
*/

/* CVS tag - DON'T TOUCH*/
#define __U_NETLOG_ID "$Id$"

#define _DBG_LEVEL_ 10

#include "alcugs.h"
#include "urunet/unet.h"

#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#include "alcdebug.h"

namespace alc {

/** gets the ip address string of a host ip in network byte order
*/
char * alcGetStrIp(U32 ip) {
	in_addr cip;
	static char mip[16];
	cip.s_addr=(unsigned long)ip;
	strcpy(mip, inet_ntoa(cip));
	//print2log(f_uru,"DBGDBGDBG:<<<----->>>>%s:%08X\n",mip,ip);
	return mip;
}

#if 0
/**
	Returns the string explaining the error that ocurred
*/

const char * alcGetStrUnetErr(S16 code) {
	switch (code) {
		case UNET_REJECTED:
			return "The connection was rejected";
		case UNET_TOMCONS:
			return "Reached the maxium number of connections supported by this system";
		case UNET_NONURU:
			return "Ignored a non-uru message, generated by another protocol, a port scan, or another unknown system";
		case UNET_CRCERR:
			return "Ignored an incomming message due to a checksum missmatch";
		case UNET_TOOBIG:
			return "The message was discarded, because it was biggest than the Uru maxium transmission unit";
		case UNET_ERR:
			return "A generic system error occurred";
		case UNET_NOBIND:
			return "Cannot bind to the requested address";
		case UNET_INHOST:
			return "Cannot resolve or bind the requested address";
		case UNET_FINIT:
			return "Fatal error occurred on netcore initialization";
		case UNET_OK:
			return "The last operation was succesfull";
		case UNET_MSGRCV:
			return "A new message has been recieved";
		case UNET_NEWCONN:
			return "A new connection has been stablished";
		case UNET_TIMEOUT:
			return "Connection timeout";
		case UNET_TERMINATED:
			return "Connection terminated by peer";
		case UNET_FLOOD:
			return "The Peer is flooding the netcore";
		default:
			return "Undefined, unexpected, unknown and unwanted error code";
	}
}

#endif

}


